In [1]:
np.any()

NameError: name 'np' is not defined

In [61]:
import numpy as np

def generateBoardStates(shipSize):
    board_size = 10
    ship_sizes = [shipSize]
    board_states = []
    
    def is_valid_placement(board, size, x, y, direction):
        if direction == 0:
            return x + size <= board_size and np.all(board[y, x:x+size] == 0)
        elif direction == 1:
            return y + size <= board_size and np.all(board[y:y+size, x] == 0)
        return False
    
    def place_ship(board, size, x, y, direction):
        if direction == 0:
            board[y, x:x+size] = 1
        elif direction == 1:
            board[y:y+size, x] = 1
    
    def remove_ship(board, size, x, y, direction):
        if direction == 0:
            board[y, x:x+size] = 0
        elif direction == 1:
            board[y:y+size, x] = 0
    
    def generate(board, remaining_ships):
        if not remaining_ships:
            board_states.append(np.ravel(board.copy()))
            return
        
        ship_size = remaining_ships[0]
        
        for x in range(board_size):
            for y in range(board_size):
                for direction in [0, 1]:
                    if is_valid_placement(board, ship_size, x, y, direction):
                        place_ship(board, ship_size, x, y, direction)
                        generate(board, remaining_ships[1:])
                        remove_ship(board, ship_size, x, y, direction)
    
    empty_board = np.zeros((board_size, board_size), dtype=int)
    generate(empty_board, ship_sizes)
    
    return np.array(board_states)

# Example usage:
board_states = np.empty((0, 100))

three_board_states = generateBoardStates(3)
two_board_states = generateBoardStates(2)
five_board_states = generateBoardStates(5)
four_board_states = generateBoardStates(4)

board_states = np.concatenate((board_states, three_board_states), 0)
board_states = np.concatenate((board_states, three_board_states), 0)
board_states = np.concatenate((board_states, four_board_states), 0)
board_states = np.concatenate((board_states, five_board_states), 0)
board_states = np.concatenate((board_states, two_board_states), 0)

probability = np.zeros(100)
for state in board_states:
    probability += state
print(probability.reshape((10, 10)))


validity = [True] * len(board_states)
for i in range(len(board_states)):
    shot = (5,5)
    shotIndex = (shot[0] - 1) * 10 + shot[1] - 1
    if board_states[i][shotIndex] != 1:
        validity[i] = False

for i in range(len(board_states)):
    shot = (5,6)
    shotIndex = (shot[0] - 1) * 10 + shot[1] - 1
    if board_states[i][shotIndex] != 1:
        validity[i] = False
        
for i in range(len(board_states)):
    shot = (5,7)
    shotIndex = (shot[0] - 1) * 10 + shot[1] - 1
    if board_states[i][shotIndex] != 1:
        validity[i] = False

for i in range(len(board_states)):
    shot = (5,8)
    shotIndex = (shot[0] - 1) * 10 + shot[1] - 1
    if board_states[i][shotIndex] != 1:
        validity[i] = False

for i in range(len(board_states)):
    shot = (5,9)
    shotIndex = (shot[0] - 1) * 10 + shot[1] - 1
    if board_states[i][shotIndex] != 1:
        validity[i] = False

for i in range(len(board_states)):
    shot = (5,10)
    shotIndex = (shot[0] - 1) * 10 + shot[1] - 1
    if board_states[i][shotIndex] != 1:
        validity[i] = False

board_states = board_states[validity]
probability = np.zeros(100)
for state in board_states:
    probability += state
probability[shotIndex] = 0
print(probability.reshape((10, 10)))


[[10. 15. 19. 21. 22. 22. 21. 19. 15. 10.]
 [15. 20. 24. 26. 27. 27. 26. 24. 20. 15.]
 [19. 24. 28. 30. 31. 31. 30. 28. 24. 19.]
 [21. 26. 30. 32. 33. 33. 32. 30. 26. 21.]
 [22. 27. 31. 33. 34. 34. 33. 31. 27. 22.]
 [22. 27. 31. 33. 34. 34. 33. 31. 27. 22.]
 [21. 26. 30. 32. 33. 33. 32. 30. 26. 21.]
 [19. 24. 28. 30. 31. 31. 30. 28. 24. 19.]
 [15. 20. 24. 26. 27. 27. 26. 24. 20. 15.]
 [10. 15. 19. 21. 22. 22. 21. 19. 15. 10.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [4]:
import numpy as np
np.all(np.ones(100) == 0)

False